
apiVersion: v1  # 主要是指定版本，这个没有什么好说的
kind: Pod
metadata:  # 元数据相关  一般有name和labels就足够了
  name: damn-it-pod  # 启动docker的时候可以不给容器取名字，但是pod必须有名字,所以这里给pod取名
  labels: # 下面都是标签了，
    owner: wulinlin  
    env: demo
    region: north
    tier: back
spec: # 需要管理、维护 Pod 这个 Kubernetes 的基本调度单元，里面有非常多的关键信息，
  containers:  # 这是个数组 用于指定一个或者多个容器 每个容器是一个container对象(容器对象)
  - image: nginx:latest # 指定镜像
    name: ngx  # 容器对象也必须要有名字
    imagePullPolicy: IfNotPresent  # 通常是IfNotPresent 也就是说如果本地不存在镜像才去会拉取镜像(减少网络消耗)
    env:  # 用于定义Pod的环境变量，和Docker中的ENV指令有点点像
      - name: os
        value: "ubuntu"
      - name: debug
        value: "on"
    command:  # 主要是用来定义容器启动时要执行的命令，相当于docker中的ENTRYPOINT命令
      - /bin/echo
    args:
      - "$(os), $(debug)"